version: "3"
services:
  react-test-run:
    build:
      context: .
      dockerfile: Dockerfile.prod
      # args:
      #   - REACT_APP_NAME=Yousefyml-prod-to_make_sure_it_works
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - REACT_APP_NAME=Yousefyml-prod
    # env_file:
    # - ./.env
